network:
  version: 2
  renderer: networkd

#this configuration is for the OOB (Out-Of-Band) management of the host only.

  ethernets:
    ens3: #change this to you out-of-band management port
      dhcp4: false
      dhcp6: false
      addresses:
      - 10.0.22.3/24 #change this to the IP you want to assign
      routes:
      - to: default
        via: 10.0.22.254 #change this to the gateway of interface
      nameservers:
        addresses: [8.8.8.8] #change to whatever the DNS you want to use
