network:
  version: 2
  renderer: networkd

  bridges:
    br0:
      interfaces: []
      optional: true

  vlans:
    br0.2201:
      id: 2201
      link: br0
      addresses:
        - 10.10.3.2/24
      nameservers:
        addresses: [10.10.3.22, 8.8.8.8]
      routes:
        - to: 0.0.0.0/0
          via: 10.10.3.1
